#!/bin/bash

# andromeda_stats: Show stats about andromeda homelab server

kubectl --kubeconfig ~/.kube/configs/andromeda.yaml top node &> /dev/null
if [ "$?" -ne 0 ];then
  echo "Andromeda: Unhealthy"
  exit 1
fi

cpu=$(kubectl --kubeconfig ~/.kube/configs/andromeda.yaml top node | tail -n 1 | tr -s ' ' | cut -d' ' -f3)
mem=$(kubectl --kubeconfig ~/.kube/configs/andromeda.yaml top node | tail -n 1 | tr -s ' ' | cut -d' ' -f5)

echo "Andromeda:   $cpu   $mem"
