#!/usr/bin/env bash

# backup_nuc_restic: Backup workspace to s3/b2 using restic

# Use the env variables to export credentials and repo

# export AWS_ACCESS_KEY_ID=
# export AWS_ACCESS_KEY_ID=
# export RESTIC_PASSWORD=
# export RESTIC_REPOSITORY=

# shellcheck source=/dev/null
source ~/private/restic/env

restic --verbose backup ~/.config/BraveSoftware ~/workspace


# Cleanup old backups
restic forget --keep-monthly 12 --keep-last 10 --keep-daily 10 --prune

TZ='Europe/Berlin' date +"%Y-%m-%d %H:%M:%S %Z" > ~/workspace/backups/last_backup_date
