#!/bin/bash

# backup_workspace_restic: Backup workspace to wasabi using restic

# Use the env variables to export credentials and repo

# export AWS_ACCESS_KEY_ID=
# export AWS_ACCESS_KEY_ID=
# export RESTIC_PASSWORD=

export RESTIC_REPOSITORY="s3:https://s3.eu-central-2.wasabisys.com/jd.workspace.backup"

source ~/private/restic/env

restic --verbose backup ~/workspace/

