#!/bin/bash

# backup_ssd: Backup workspace to local ssd

DISK_NAME=backup
# First find where the SSD is mounted

mount=$(lsblk | grep $DISK_NAME | awk '{print $7}')
[ -z $mount ] && echo "Disk not found" && exit 1
echo $mount

~/workspace/scripts/prepare_backup.sh


echo "---------------backing up to ssd-----------------"

rsync -avhP ~/workspace $mount/backup --delete
# rclone sync ~/workspace $mount/backup/workspace -P -v --copy-links

echo "---------------backed up to ssd-----------------"
