#!/bin/bash

# backup_workspace_restic: Backup workspace to wasabi using restic

# Use the env variables to export credentials and repo

# export AWS_ACCESS_KEY_ID=
# export AWS_ACCESS_KEY_ID=
# export RESTIC_PASSWORD=
# export RESTIC_REPOSITORY=

source ~/private/restic/env

restic --verbose backup ~/.config/BraveSoftware
restic --verbose backup ~/workspace/

