#!/bin/bash

# backup_ssd: Backup workspace to local ssd


DISK_NAME=backup

read -n 1 -p "This will copy files from local workspace into SSD disk named $DISK_NAME, are you sure you want to continue? (y/N) : " p
echo

if [ "$p" != "y" ];then
  exit 1
fi


# First find where the SSD is mounted

mount=$(lsblk | grep $DISK_NAME | awk '{print $7}')
[ -z $mount ] && echo "Disk not found" && exit 1
echo $mount

# ~/workspace/scripts/prepare_backup.sh


echo "---------------backing up to ssd-----------------"

# Sync the whole workspace
rsync -avhP ~/workspace $mount/backup --delete
# Sync the private stuff
rsync -avhP ~/private $mount/backup --delete
# rclone sync ~/workspace $mount/backup/workspace -P -v --copy-links

echo "---------------backed up to ssd-----------------"
