#!/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin:~/workspace/scripts

# backup_private: Backup secure and private stuff
# map and notes are pushed to private git repos
# taskwarrior is synced to taskserver
# private folder is synced to wasabi (encrypted)

notes push
map push
task sync
cp /home/jayadeep/.config/gcloud /home/jayadeep/private -r
cp /home/jayadeep/.kube/* /home/jayadeep/private/kube/ -r

# Use the env variables to export credentials and repo

# export AWS_ACCESS_KEY_ID=
# export AWS_ACCESS_KEY_ID=
# export RESTIC_PASSWORD=
# export RESTIC_REPOSITORY=

source ~/private/restic/env-private

restic --verbose backup /home/jayadeep/private

