#!/bin/sh

## To fix monitor not waking up from sleep, just change its resolution and change it back
xrandr --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --mode 1024x768 --pos 1920x0 --rotate normal --output HDMI-1 --off
xrandr --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --mode 1366x768 --pos 1920x0 --rotate normal --output HDMI-1 --off

