#!/bin/bash

# myvpn: manage my wireguard vpn connections
# dependencies: wg-quick

declare -A VPNS=(
  [us]="/home/jayadeep/workspace/vpn/wg0-client-arch.conf"
  [in]="/home/jayadeep/workspace/vpn/in-client-arch.conf"
)


usage() {
  echo "
Manage wireguard VPN connections

usage:
$(basename $0) us/in up/down
  "
}

if [ "$#" != "2" ]; then
  usage
	exit 1
fi

wg-quick $2 ${VPNS[$1]}
