#!/bin/bash

usage() {
  echo "notes : Take notes in markdown

  notes                   # Fuzzy finder to select a note and edit it in nvim
  notes open              # Fuzzy finder to select a note and open in browser
  notes list              # List notes as a tree
  notes preview           # Preview note in bat
  notes commit mycommit   # Commit notes to git with message mycommit"
}

getFile() {
  file=$(find ~/private/notes -type f -name "*.md" -not -path '*/.git/*' | cut -sd / -f 6- | fzf --preview 'bat --style numbers,changes --color always ~/private/notes/{}')
  echo $file
}

push() {
  msg=$1
  if [[ -z $msg ]]
  then
    msg="Notes saved on : $(date)"
  fi
  cd ~/private/notes ; git add .; git commit -m "$msg"; git push origin main;
}

open() {
  file=$(getFile)
  if [[ -z $file ]]
  then
    echo "No file specified"
    exit 1
  fi
  google-chrome-stable "~/private/notes/$file"
}

preview() {
  file=$(getFile)
  if [[ -z $file ]]
  then
    echo "No file specified"
    exit 1
  fi
  which bat &> /dev/null
  if [ $? == 0 ];then
    bat -p ~/private/notes/$file
  else
    cat p ~/private/notes/$file
  fi
}

list() {
  tree ~/private/notes
}

edit() {
  file=$(getFile)
  if [[ -z $file ]]
  then
    echo "No file specified"
    exit 1
  fi

  cd ~/private/notes; nvim $file
}

if [ "$#" == "0" ]; then
  edit
	exit 1
fi

cmd=$1
shift

case $cmd in 
   edit)
     edit
;;
   list)
     list
;;
   open)
     open
;;
   preview)
     preview
;;
   push)
     push $1
;;
   *)
     usage
     exit 1
;;
esac
