#!/bin/sh

connection=$(pgrep -a openvpn$ | head -n 1 | awk '{print $NF }' | cut -d '.' -f 1)
ip="$(curl -sf -4 ifconfig.io)"
ip6="$(curl -sf -6 ifconfig.io)"

if [ -n "$connection" ]; then
  personalVpn=$(cat ~/workspace/vpn/jd_arch.ovpn | grep remote\  | cut -d" " -f2)
  case $ip in
    $personalVpn)
      type="vpn(personal): "
      ;;

    *)
      type="vpn(work): "
      ;;
  esac
else 
  type=""
fi

echo "%{F#0ff} %{F-}$type %{F#0fc}$ip%{F-}%{F#0cf} $ip6${F-}"

