#!/usr/bin/env bash

# resticman: A wrapper over restic with predefined configurations

declare -A REPOS=(
  [nuc]="NUC workspace backup"
  [private]="Private files backup"
  [andromeda-pihole]="Andromeda cluster backup for pihole"
  [andromeda-monitoring]="Andromeda cluster backup for monitoring"
  [milkyway-pihole]="Milkyway cluster backup for pihole"
  [psuite-backup]="Psuite backup"
  [psuite-andromeda]="Psuite Andromeda backup"
  [postgres-cosmos]="Postgres cosmos backup"
  [ssd]="NUC backup in ssd"
)

usage() {
  echo "resticman: A wrapper over restic
    resticman [reponame] [restic arguments]
  "
  echo "Available repos: " "${!REPOS[@]}"
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi


if [[ -z "${REPOS[$1]}" ]] 
then
  echo "Invalid repo: $1"
  echo
  usage
  exit 1
fi

# shellcheck source=/dev/null
source "$HOME/private/restic/env-$1"

shift
restic "$@"
