#!/bin/bash

# restore: Restore workspace from local ssd

DISK_NAME=backup
read -n 1 -p "This will copy files from SSD disk named $DISK_NAME to local workspace, are you sure you want to continue? (y/N) : " p
echo

if [ "$p" != "y" ];then
  exit 1
fi

# First find where the SSD is mounted
mount=$(lsblk | grep $DISK_NAME | awk '{print $7}')
[ -z $mount ] && echo "Disk not found" && exit 1
echo $mount


echo "---------------restoring from ssd-----------------"

rsync -avhP $mount/backup/workspace/ ~/workspace/ --delete

echo "---------------restored from ssd-----------------"
