#!/usr/bin/env bash

# todo: show tasks for today

count() {
  # Task due in todo folder
  pending=$(task folder:todo status:pending count 2>/dev/null)

  # Tasks done today
  done=$(task end.after:today status:completed count 2>/dev/null)

  # Total tasks done+pending today
  total=$((pending+done))

  # Tasks currently working on (including waiting)
  started=$(task start.any: status:pending count 2>/dev/null)

  # New tasks in inbox
  inbox=$(task folder:in status:pending count 2>/dev/null)

  echo "Tasks:   $done/$total |   $started |   $inbox"
}

show() {
  task folder:todo
}

if [ "$#" == "0" ]; then
  show
  exit 0
fi

cmd=$1
shift

case $cmd in 
   count)
     count
;;
   *)
     show
;;
esac

