#!/usr/bin/env bash

# todo: show tasks for today

count() {
  # Task due for today
  pending=$(task scheduled.before:tomorrow status:pending count 2>/dev/null)

  # Tasks done today
  done=$(task end.after:today status:completed count 2>/dev/null)

  # Total tasks done+pending today
  total=$((pending+done))

  # Tasks currently working on (including waiting)
  started=$(task start.any: status:pending count 2>/dev/null)

  # New tasks in inbox
  inbox=$(task status:pending project: count 2>/dev/null)

  echo "Tasks:   $done/$total |   $started |   $inbox"
}

show() {
  task today
}

current() {
  if [ "$(task start.any: status:pending count 2>/dev/null)" -eq "0" ];then
    exit 1
  fi
  task start.any: status:pending export | jq -r '.[0] | (.id | tostring) + ":" + .project + ": " + .description'
}

display() {
  # Task due for today
  pending=$(task scheduled.before:tomorrow status:pending count 2>/dev/null)

  # Tasks done today
  done=$(task end.after:today status:completed count 2>/dev/null)

  # Total tasks done+pending today
  total=$((pending+done))

  # New tasks in inbox
  inbox=$(task status:pending project: count 2>/dev/null)

  curr=$(current)

  echo "TODO:   $done/$total |   $inbox |  $curr"
}



if [ "$#" == "0" ]; then
  show
  exit 0
fi

cmd=$1
shift

case $cmd in 
   count)
     count
;;
   current)
     current
;;
   display)
     display
;;
   *)
     show
;;
esac
