#!/bin/bash

# usedns: Set system dns based on predefined config

usage() {
  echo "usedns: set system dns based on predefined resolvconf.conf
    usedns [name]
  "
  echo "Available configs: default, homelab"
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

sudo cp "/etc/resolvconf.conf-$1" "/etc/resolvconf.conf"
sudo resolvconf -u
