#! /bin/sh

# Command to quickly create/edit scripts in ~/workspace/scripts directory

if [ -z $1 ]; then
  echo "Enter a file name as \`vic [NAME]\`"
  exit 1
fi

FILE=~/workspace/scripts/$1

if [ ! -f "$FILE" ]; then
  read -p "File doesn't exist. Create? y/N : " c
  if [ "$c" = "y" ]; then
    echo "#!/bin/bash" > $FILE
    echo "" >> $FILE
    echo "# $1:" >> $FILE
    chmod +x $FILE
  else
    exit 0
  fi
fi

cd ~/workspace/scripts
$EDITOR $FILE
