#!/bin/bash

# xrestic: Restic with predefined env variables to access backup

# Use the env variables to export credentials and repo

# export AWS_ACCESS_KEY_ID=
# export AWS_ACCESS_KEY_ID=
# export RESTIC_PASSWORD=

export RESTIC_REPOSITORY="s3:https://s3.eu-central-2.wasabisys.com/jd.workspace.backup"

source ~/.config/restic/env

restic "$@"
